Redesign with dark theme
schneurzsmith@iMac authority-audit % git push
To https://github.com/schneurzsmith/authority-audit.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/schneurzsmith/authority-audit.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
schneurzsmith@iMac authority-audit % git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (5/5), 1.14 KiB | 145.00 KiB/s, done.
git pusgi git pugi
git push

 for your changes. Lines starting